language: php
php:
  - "5.5"

before_isntall:
  - php /home/travis/.phpenv/versions/5.5/bin/composer self-update

before_script:
  - composer install

script: phpunit phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - alsorto@gmail.com
    on_success: change
    on_failure: always