language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"



before_script:
  - composer install

script: phpunit --configuration phpunit.xml

notifications:
  email:
    recipients:
      - alsorto@gmail.com
    on_success: change
    on_failure: always