language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - hhvm
  - nightly

before_script:
    - composer self-update
    - composer install


script: phpunit



notifications:
  email:
    recipients:
      - asorto@csumb.edu
      - hsandoval@csumb.edu
      - arlopez@csumb.edu
      - drusconi@csumb.edu
    on_success: never
    on_failure: always