language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"



before_script:
  - composer install

before_script:
    - wget https://phar.phpunit.de/phpunit.phar
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - phpunit


script: php --configuration phpunit.xml



notifications:
  email:
    recipients:
      - alsorto@gmail.com
    on_success: change
    on_failure: always