language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - hhvm
  - nightly

before_script:
    - composer install
    - wget https://phar.phpunit.de/phpunit.phar
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - phpunit

notifications:
  email:
    recipients:
      - asorto@csumb.edu
      - hsandoval@csumb.edu
      - arlopez@csumb.edu
      - drusconi@csumb.edu
    on_success: change
    on_failure: always